### ISSUE TITLE
Support for TimescaleDB compressed tables

### ISSUE THREAD

**Issue by andnofence** [duckdb/postgres_scanner#104] opened 2023-08-21 06:04 UTC
### What happens?

I wanted to try out DuckDB against our TimescaleDB database. TimescaleDB is great for the IoT data we collect, but it's not ideal as an analytics database. So when I found the DuckDB Postgres scanner I was excited as it seems we could have our cake and eat it to. Unfortunately it seems the two tools are not compatible, when trying to read data from a TimescaleDB table that uses compression I get the following error:

> Error: Invalid Error: IO Error: Unable to query Postgres: ERROR: transparent decompression only supports tableoid system column

So I'm wondering if you have looked into making the scanner compatible with TimescaleDB compressed tables?

Perhaps it would be possible to allow the scanner to fall back to a slightly less efficient manner of executing the queries (e.g. using csv output format?). I'd rather have results that are a bit slower than no results at all since most of these queries would be overnight report jobs anyway.

(I moved this from https://github.com/duckdb/duckdb/discussions/8622)

### To Reproduce

Try to read a TimescaleDB compressed table.

### OS:

Any

### PostgreSQL Version:

14, but I guess it applies to all versions

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

André Næss

### Affiliation:

Nofence AS

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-10-17 20:28
Thanks for the report! I've played around with Timescale for a bit but have not managed to hit this error message. Could you provide a reproducible example that includes the setup for TimescaleDB (i.e. schema/data insertion)?

**Comment by mosiman** [comment] 2023-10-18 01:10
Here's what I did, hopefully this is clear enough to follow along.

First, start a `timescaledb` instance. Docker container to make things a little easier to reproduce.

```
podman run \
    -it \
    -p 5432:5432 \
    -e POSTGRES_PASSWORD=password \
    timescale/timescaledb:latest-pg14
```

Run the following commands in a `psql` shell connected to this `timescaledb` instance (e.g. with ` psql -h localhost -U postgres -p 5432`, the password is `password` as configured in the docker run command.)

```
create table example_compressed_table as
select
    generate_series('2023-01-01'::timestamptz, '2023-12-31'::timestamptz, '1 minute'::interval) as ts,
    'some scalar value' as scalar
;

SELECT create_hypertable(
    'example_compressed_table',
    'ts',
    chunk_time_interval => INTERVAL '1 day',
    migrate_data => true
);
```

This should create a table with a timeseries column and another column that I don't think actually adds to anything, but thought it was weird to only have a timeseries column.

If you try querying this from `duckdb` things should still work fine.

```
❯ duckdb
v0.9.0 
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D install postgres_scanner;
D load postgres_scanner;
D CALL postgres_attach('user=postgres host=localhost port=5432 password=password');
┌─────────┐
│ Success │
│ boolean │
├─────────┤
│ 0 rows  │
└─────────┘
D PRAGMA show_tables;
┌──────────────────────────┐
│           name           │
│         varchar          │
├──────────────────────────┤
│ example_compressed_table │
└──────────────────────────┘
D select * from example_compressed_table limit 5;
┌──────────────────────────┬───────────────────┐
│            ts            │      scalar       │
│ timestamp with time zone │      varchar      │
├──────────────────────────┼───────────────────┤
│ 2022-12-31 19:00:00-05   │ some scalar value │
│ 2022-12-31 19:01:00-05   │ some scalar value │
│ 2022-12-31 19:02:00-05   │ some scalar value │
│ 2022-12-31 19:03:00-05   │ some scalar value │
│ 2022-12-31 19:04:00-05   │ some scalar value │
└──────────────────────────┴───────────────────┘
```

The trick is to make this a compressed hypertable and compress the chunks. Switch back over to your `psql` shell and run the following:

```
alter table example_compressed_table set (
    timescaledb.compress
);

SELECT compress_chunk(i, if_not_compressed => true)
    FROM show_chunks(
        'example_compressed_table'
    ) i;
```

Now if you try to query again from `duckdb`, you'll get the error as described.

```
D select * from example_compressed_table limit 5;
Error: IO Error: Unable to query Postgres: ERROR:  transparent decompression only supports tableoid system column
 ERROR:  transparent decompression only supports tableoid system column
```

**Comment by Mytherin** [comment] 2023-10-18 10:43
Thanks for the reproducible example! I can indeed confirm I encounter the error with the currently released version of the Postgres scanner:

```sql
CALL postgres_attach('dbname=tsdb');
SELECT * FROM example_compressed_table;
-- Error: IO Error: Unable to query Postgres: ERROR:  transparent decompression only supports tableoid system column
--  ERROR:  transparent decompression only supports tableoid system column
```

When running with the latest version which includes the (many) changes from #111, this appears to be fixed:

```sql
attach 'postgres:dbname=tsdb' as db;
select * from db.example_compressed_table limit 5; 
┌──────────────────────────┬───────────────────┐
│            ts            │      scalar       │
│ timestamp with time zone │      varchar      │
├──────────────────────────┼───────────────────┤
│ 2022-12-31 23:59:00+00   │ some scalar value │
│ 2022-12-31 23:58:00+00   │ some scalar value │
│ 2022-12-31 23:57:00+00   │ some scalar value │
│ 2022-12-31 23:56:00+00   │ some scalar value │
│ 2022-12-31 23:55:00+00   │ some scalar value │
└──────────────────────────┴───────────────────┘
```

This seems to be because we now only do the `CTID` partitioning if there are sufficient `relpages` reported, and TimescaleDB appears to report 0 pages for compressed tables:

```sql
D SELECT relname, relpages
> FROM pg_class
> JOIN pg_namespace ON relnamespace = pg_namespace.oid
> WHERE pg_namespace.nspname='public' AND relname='example_compressed_table'
> ORDER BY relname;
┌──────────────────────────┬──────────┐
│         relname          │ relpages │
│         varchar          │  int32   │
├──────────────────────────┼──────────┤
│ example_compressed_table │        0 │
└──────────────────────────┴──────────┘
```

I would say the issue is now fixed in the latest version - at least for the given example. Feel free to re-open if you encounter issues with other tables.

**Closed by Mytherin** 2023-10-18 10:43 UTC
